### ISSUE TITLE
displaying me being on website when i have it disabled and im not on website

### ISSUE THREAD

**Issue by meowlegend100** [Daw588/stateye#10]
Stateye shows that im browsing on the website when i dont have roblox open, and my config file has it to not display website activity

**Comment by Daw588** [comment]
Is the config file named exactly `stateye.config` and it is placed next to `stateye.exe`?

**Comment by Daw588** [comment]
I'm not sure what may the issue be, try running the latest debug version of the program, and share a screenshot of the output.
