### ISSUE TITLE
StatEye latest version not working

### ISSUE THREAD

**Issue by X-Zynth** [Daw588/stateye#11]
so i did all the steps for install it, even i did the config file, but when always start it, crashes; so idk what to do

**Comment by Daw588** [comment]
My apologizes for late reply, I wasn't notified. To find source of the issue:
1. Download the debug version of the program from the latest release.
2. Open command prompt where the program is at.
3. Run the program through the command prompt.
4. Copy and paste the logs in your reply, and make sure that they don't contain any sensitive information.

![tutorial](https://github.com/Daw588/stateye/assets/44325281/7725d007-cc27-431e-a1d0-065e9f129891)

**Comment by X-Zynth** [comment]
I am using Windows 10, so I can't see that terminal button.

**Comment by X-Zynth** [comment]
i found out a way, so this is what is says
[image: image.png]

**Comment by X-Zynth** [comment]
so this is what is says
![image](https://github.com/Daw588/stateye/assets/119027866/171e2b35-aad0-494f-8472-934a58c58f08)

**Comment by Daw588** [comment]
The same issue was experienced in issue #12. Check it out.
