### ISSUE TITLE
Refuses to run.

### ISSUE THREAD

**Issue by Anoosyy** [Daw588/stateye#12]
I downloaded every single version of the stateye.exe file and none of them did anything, just a small blue circle on the cursor for a second and then nothing. I also tried running the debug application and it showed that there were no errors. Any fix?

Specs:
Ryzen 7 5700X
NVIDIA RTX 3070 Ti
16GB Ram.

Help would be extremely appreciated :)

**Comment by Daw588** [comment]
To find source of the issue:
1. Download the debug version of the program from the latest release.
2. Open command prompt where the program is at.
3. Run the program through the command prompt.
4. Copy and paste the logs in your reply, and make sure that they don't contain any sensitive information.

![tutorial](https://github.com/Daw588/stateye/assets/44325281/7725d007-cc27-431e-a1d0-065e9f129891)

**Comment by Anoosyy** [comment]
For some reason it wouldn't run the same way you showed, I had to do .\stateye_debug for it to run, but regardless here's what I got.

Application started
VERSION: 0.3.2
Config file not found, using defaults
thread 'main' panicked at 'Failed to fetch user id', src\roblox.rs:69:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Daw588** [comment]
It seems like the program can't find your Roblox account token. Are you using Roblox from Microsoft Store by any chance?

**Comment by Anoosyy** [comment]
No, I downloaded it from the website. The Microsoft version is clunky and sluggish for me.

**Comment by Daw588** [comment]
I'm not sure why it fails to get your Roblox account token. For now, you will have to manually enter the token through the configuration file. Keep in mind that it will change whenever you change your credentials (e.g., password, etc.), and probably on logging out too.

**Comment by Anoosyy** [comment]
Can you guide me through doing that. I have no clue in the slightest on how to start on doing the fix you suggested.

**Comment by Daw588** [comment]
**WARNING: DO NOT EVER SHARE THE TOKEN WITH ANYONE AS IT WILL ALLOW ANYONE TO LOGIN INTO YOUR ACCOUNT WITHOUT THE NEED OF A PASSWORD AND OTHER SECURITY METHODS ASSOCIATED WITH THE ACCOUNT!**

The instructions are as follows:
1. Navigate to [roblox.com](https://www.roblox.com/home) in your browser.
2. Right click anywhere on the page.
3. Choose the "Inspect" option.
4. Click on "Application" tab.
5. Under Storage section, select the first item under "Cookies".
6. In the list click on ".ROBLOSECURITY".
7. Copy the long text under "Cookie Value".
8. Create `stateye.config` file where the executable (program) is located at.
9. Write `token=REPLACE_THIS_UPPERCASE_TEXT_WITH_YOUR_TOKEN`.
10. Open the executable (program).

![image](https://github.com/Daw588/stateye/assets/44325281/3604c266-b3c0-4368-9585-1cb30671131c)
![image](https://github.com/Daw588/stateye/assets/44325281/07bb9145-f064-43d5-bb6f-a09c0a5b99c0)
![image](https://github.com/Daw588/stateye/assets/44325281/4d10e20d-8b5f-458e-9b0e-0ef089ed4d8d)
![image](https://github.com/Daw588/stateye/assets/44325281/1a8f304c-2cd9-4c7b-a7c7-b606c28ed5f0)
![image](https://github.com/Daw588/stateye/assets/44325281/cdebc713-74a7-4a4d-bd03-8f0b6a1da0c5)

**Comment by X-Zynth** [comment]
i did the same, but i have still the same error

**Comment by Anoosyy** [comment]
Sorry to be a nuisance, but this fix didn't work. I created file "stateye.config" as a text document, perhaps that might be an issue? Other than that nothing seems to be working. I tried also running it as administrator and still nothing. Unless it's something like copying the warning before your token, I don't see what the problem can be.

**Comment by Daw588** [comment]
Can you send me the logs from the debug version when the config file is present?

**Comment by X-Zynth** [comment]
its the same error code

**Comment by Daw588** [comment]
I understand that, however, I would like to see the logs since the logs themselves may differ besides the error.

**Comment by X-Zynth** [comment]
Loaded config from C:\Users\\Documents\Roblox Stat Eye\stateye.config
thread 'main' panicked at 'Failed to fetch user id', src\roblox.rs:69:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Daw588** [comment]
It appears that the program loaded in the configuration file. Have you copied the full token properly without any additional characters such as spaces?

**Comment by X-Zynth** [comment]
i copied only the full token

**Comment by Daw588** [comment]
I am afraid that I cannot do much more to help. But I will try to look into Roblox's OAuth2 API and see if this can make things easier, and more reliable. Allow me approximately 2 weeks to write an alternative solution to this application.

**Comment by Anoosyy** [comment]
Thanks for your help. Not many creators try to help as much as you ❤️.

**Comment by X-Zynth** [comment]
2 weeks? damn, welp thanks anyways tho

**Comment by Daw588** [comment]
I have tested the usage of OAuth2 API, but it appears that it is not sufficient yet to detect current status without being logged in (`.ROBLOSECURITY`). I do not think I can do more to help due to the nature of token being a private piece information. For the time being I will just recommend using a different tool.
