### ISSUE TITLE
config file not found

### ISSUE THREAD

**Issue by xXAGENT87Xx** [Daw588/stateye#13]
i have a .config file named stateye.config and its still saying config file not found

**Comment by Daw588** [comment]
Did you place the file next to the `.exe` program?

**Comment by xXAGENT87Xx** [comment]
what do you mean

**Comment by Daw588** [comment]
You must have `stateye.config` in the same folder as `stateye.eye`.

**Comment by xXAGENT87Xx** [comment]
it is

**Comment by Daw588** [comment]
How do you know? Did you check with the debug version of StatEye? If so, can you provide more information about your system, and Roblox installation?

- Operating system (e.g., Windows, MacOS, Linux)
- Operating system version (e.g., Windows 11 Pro 22H2)
- Roblox installation type (e.g., Roblox.com, Microsoft Store App)

Additionally, provide logs from the debug version of StatEye, ideally a copy+paste of entire logs.

**Comment by xXAGENT87Xx** [comment]
1 windows
2 Windows 11 Home 22H2
roblox.com

**Comment by xXAGENT87Xx** [comment]
how do i get logs from the debug

**Comment by Daw588** [comment]
Just download the debug version from the latest release, run the program, and take a screenshot, or copy+paste the contents.
