### ISSUE TITLE
Stateye refuses to open

### ISSUE THREAD

**Issue by Z7arato** [Daw588/stateye#14]
i run stateye and literally nothing happens. I'm using the latest version , Roblox Windows version and i also tried  running it with a config file in the same folder.

thread 'main' panicked at 'Failed to fetch user id', src\roblox.rs:69:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Daw588** [comment]
The same issue was experienced in issue #12. Check it out.
