### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by githubuser29845945** [Daw588/stateye#18]
I have my config file in the same directory as stateye.exe and when i run debug through cmd it says config wasnt found

![image](https://github.com/Daw588/stateye/assets/159243899/52b01052-07e4-43cf-9193-6363eb7bc859)
![image](https://github.com/Daw588/stateye/assets/159243899/4561f6ac-b84e-49ba-bbb8-7c65709e4da1)

**Comment by githubuser29845945** [comment]
Application started
VERSION: 0.3.3
Config file not found, using defaults
thread 'main' panicked at 'Failed to fetch user id', src\roblox.rs:60:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by githubuser29845945** [comment]
this is what my config file looks like
![image](https://github.com/Daw588/stateye/assets/159243899/c5632885-7a4d-4bc1-8219-869fb3f3020f)

**Comment by ohareza** [comment]
Your config file has a a hidden .txt extension

**Comment by Daw588** [comment]
I'm sorry, I forgot to respond! @ohareza you are most likely right, I completely forgot about this possibility since I have file extensions turned on.
