### ISSUE TITLE
Panic: failed to fetch userid

### ISSUE THREAD

**Issue by Renen12** [Daw588/stateye#19]
Application started
VERSION: 0.3.3
Config file not found, using defaults
thread 'main' panicked at 'Failed to fetch user id', src\roblox.rs:60:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
I am using windows, and when I visit the url it gives me the user id and som other information? Is there anything wrong with how the headers are recieved or am I comletely wrong?

**Comment by Daw588** [comment]
The program is most likely failing to find your Roblox account token. I haven't wrote the library that does this, so I'm unsure what the issue possibly is.

**Comment by Renen12** [comment]
No idea, sorry for this issue
