### ISSUE TITLE
Stateye crashes on launch

### ISSUE THREAD

**Issue by BeliyDot** [Daw588/stateye#3]
It just crashes on launch, both standard & debug versions.

My specs:
Lenovo Ideapad Gaming 3 15IAH (RTX 3050/i5-12450H/16 GB RAM)
Windows 11 Pro
Video-demonstration:
https://github.com/Daw588/stateye/assets/133781890/a1a667bd-401c-4743-b05f-f749bc828ad2

**Comment by BeliyDot** [comment]
> Can you try running the debug program through a command line? I think you just need to type the file name (don't include `.exe` extension) of the program and make sure that CMD is running in the same dictionary. Hopefully this will be sufficient enough for you to collect the logs.

Okay, I followed your advice, and after running it in the CMD I've got this: 
![image](https://github.com/Daw588/stateye/assets/133781890/733f7ed6-53f6-428b-abcf-e3f27e144cf4)

**Comment by Daw588** [comment]
Do you have Roblox Studio installed? If not, try installing it, and make sure to login in, then try again and see if the program works. I suspect that the automated system that grabs the token fails to grab one.

If the following still doesn't work, try to get your `.ROBLOSECURITY` token cookie manually and put it inside of a configuration file for the program.

**Comment by BeliyDot** [comment]
And also after some random time it crashes.

**Comment by Daw588** [comment]
Have you waited a bit for Roblox to detect your activity? Also, for the random crash issue, try launching the debug version through CMD again and gather the logs.

**Comment by BeliyDot** [comment]
By some kind of magic it started to work correctly, my status shows the game I play in Discord, & the program doesn't crash anymore. Thx for help.

**Comment by LingleDev** [comment]
I get this error also. I tried every suggested fix in this post, but it still does not work.
