### ISSUE TITLE
StatEye Discord Rich Presence Problem

### ISSUE THREAD

**Issue by B8nee** [Daw588/stateye#4]
When I use StatEye everything works fine, when I turn off Roblox it keeps saying I'm browsing modes like I have the app or site open, when in fact it's closed, what should I do?

**Comment by Daw588** [comment]
It's most likely Roblox reporting wrong information, have you checked your own Roblox profile? Check and see if the status information reported by stateye matches what Roblox is reporting.

**Comment by B8nee** [comment]
I will check

**Comment by Daw588** [comment]
Due to lack of follow up, I'm closing this issue. If you are still encountering the issue, please let me know.
