### ISSUE TITLE
crashes when roblox studio opened

### ISSUE THREAD

**Issue by meowlegend100** [Daw588/stateye#5]
when i open a project in roblox studio, stateye crashes.

**Comment by 1issah** [comment]
after using stateye a little more ive realised it just closes itself all the time or something i have to keep reopening it and it doesnt work with studio at all

**Comment by Daw588** [comment]
I will look into this, thanks for the report!

**Comment by Daw588** [comment]
Does [v0.3.2](https://github.com/Daw588/stateye/releases/tag/v0.3.2) fix the issue for yall?
