### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by BrokenKaneki** [Daw588/stateye#6]
the method of set up is very unclear, and running the "stateye.exe" on it's own won't open

**Comment by Daw588** [comment]
I will look into this eventually, thank you for the report. It would be great if you could provide your system information, such as the operating system, CPU, etc.

**Comment by Daw588** [comment]
Does [v0.3.2](https://github.com/Daw588/stateye/releases/tag/v0.3.2) fix the issue for you?
