### ISSUE TITLE
Roblox Studio Doesnt Give Any RPC While Everything Else Works Properly

### ISSUE THREAD

**Issue by TTVMythical** [Daw588/stateye#7]

**Comment by TTVMythical** [comment]
i forgot to write a message lmao. i used the debug version and it is realizing that im in studio but i get no rpc while developing my game

**Comment by TTVMythical** [comment]
actually update: no rpc shows for some weird reason, it can still tell im InGame or InStudio but it wont show rpc, do i need an application or something?

**Comment by Daw588** [comment]
Does [v0.3.2](https://github.com/Daw588/stateye/releases/tag/v0.3.2) fix the issue for you?

**Comment by Daw588** [comment]
Due to lack of follow up, I'm closing this issue. If you are still encountering the issue, please let me know.
